app/src/Entity/EntityPeople.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EntityPeopleRepository")
 */
class EntityPeople
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstname;

    /**
     * @ORM\Column(type="date")
     */
    private $birthdate;

    /**
     * @ORM\Column(type="boolean")
     */
    private $newsletter;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $postal_code;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $city;

    /**
     * @ORM\Column(type="date")
     */
    private $add_date;

    /**
     * @ORM\Column(type="string", length=24)
     */
    private $sheet_id;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\TagsAffect", mappedBy="person", orphanRemoval=true)
     */
    private $tagsAffects;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\EntityInstitutions", inversedBy="entityPeople")
     * @ORM\JoinColumn(nullable=false)
     */
    private $institution;

    public function __construct()
    {
        $this->tagsAffects = new ArrayCollection();
    }

    public function __toString() {
        return $this->name." ".$this->firstname;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getBirthdate(): ?\DateTimeInterface
    {
        return $this->birthdate;
    }

    public function setBirthdate(\DateTimeInterface $birthdate): self
    {
        $this->birthdate = $birthdate;

        return $this;
    }

    public function getNewsletter(): ?bool
    {
        return $this->newsletter;
    }

    public function setNewsletter(bool $newsletter): self
    {
        $this->newsletter = $newsletter;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(?string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAddDate(): ?\DateTimeInterface
    {
        return $this->add_date;
    }

    public function setAddDate(\DateTimeInterface $add_date): self
    {
        $this->add_date = $add_date;

        return $this;
    }

    public function getSheetId(): ?string
    {
        return $this->sheet_id;
    }

    public function setSheetId(string $sheet_id): self
    {
        $this->sheet_id = $sheet_id;

        return $this;
    }

    /**
     * @return Collection|TagsAffect[]
     */
    public function getTagsAffects(): Collection
    {
        return $this->tagsAffects;
    }

    public function addTagsAffect(TagsAffect $tagsAffect): self
    {
        if (!$this->tagsAffects->contains($tagsAffect)) {
            $this->tagsAffects[] = $tagsAffect;
            $tagsAffect->setPerson($this);
        }

        return $this;
    }

    public function removeTagsAffect(TagsAffect $tagsAffect): self
    {
        if ($this->tagsAffects->contains($tagsAffect)) {
            $this->tagsAffects->removeElement($tagsAffect);
            // set the owning side to null (unless already changed)
            if ($tagsAffect->getPerson() === $this) {
                $tagsAffect->setPerson(null);
            }
        }

        return $this;
    }

    public function getInstitution(): ?EntityInstitutions
    {
        return $this->institution;
    }

    public function setInstitution(?EntityInstitutions $institution): self
    {
        $this->institution = $institution;

        return $this;
    }

}

app/src/Form/EntityPeopleType.php
<?php

namespace App\Form;

use App\Entity\EntityPeople;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use App\Form\TagsAffectType;

class EntityPeopleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name',null,array('label' => 'Nom'))
            ->add('firstname', null,array('label' => 'Prénom'))
            ->add('birthdate', null,array('label' => 'Date de naissance'))
            ->add('newsletter', null,array('label' => 'Abonnement Newsletter'))
            ->add('postal_code', null,array('label' => 'Code postal'))
            ->add('city', null,array('label' => 'Ville'))
            ->add('institution', null,array('label' => 'Institution'))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => EntityPeople::class,
        ]);
    }
}

app/src/Controller/EntityPeopleController.php
<?php

namespace App\Controller;

use App\Entity\EntityPeople;
use App\Form\EntityPeopleType;
use App\Repository\EntityPeopleRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Utils\MongoManager;

/**
 * @Route("/manager/people")
 */
class EntityPeopleController extends AbstractController
{
    /**
     * @Route("/", name="manager/entity_people_index", methods="GET")
     */
    public function index(EntityPeopleRepository $entityPeopleRepository): Response
    {
        //filtres à appliquer ici
        return $this->render('entity_people/index.html.twig', ['entity_people' => $entityPeopleRepository->findAll()]);
    }

    /**
     * @Route("/new", name="manager/entity_people_new", methods="GET|POST")
     */
    public function new(Request $request): Response
    {
        $entityPerson = new EntityPeople();
        $form = $this->createForm(EntityPeopleType::class, $entityPerson);
        $form->handleRequest($request);
        $mongoman = new MongoManager();

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();

            // Mise en bdd Mongo de l fiche doc --> return IdMongo
            if (null != $request->request->get('person_data')){
                $sheetId=$mongoman->insertSingle("Entity_person_sheet",$request->request->get('person_data'));
            }else{
                $sheetId=$mongoman->insertSingle("Entity_person_sheet",[]);
            }

            // Mise en bdd MySQL de l'ID de fiche de données
            $entityPerson->setSheetId($sheetId);
            $entityPerson->setAddDate(new \DateTime("now"));

            $em->persist($entityPerson);
            $em->flush();

            return $this->redirectToRoute('manager/entity_people_index');
        }

        return $this->render('entity_people/new.html.twig', [
            'entity_person' => $entityPerson,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="manager/entity_people_show", methods="GET")
     */
    public function show(EntityPeople $entityPerson): Response
    {

        return $this->render('entity_people/show.html.twig', ['entity_person' => $entityPerson]);
    }

    /**
     * @Route("/{id}/edit", name="manager/entity_people_edit", methods="GET|POST")
     */
    public function edit(Request $request, EntityPeople $entityPerson): Response
    {
        $form = $this->createForm(EntityPeopleType::class, $entityPerson);
        $form->handleRequest($request);
        $mongoman = new MongoManager();

        if ($form->isSubmitted() && $form->isValid()) {
            if (null != $request->request->get('person_data')){
                $dataId=$entityPerson->getSheetId();
                foreach( $request->request->get('person_data') as $key->$value){
                    if ($value!=''){
                        $mongoman->updateSingleValueById("Entity_person_sheet",$dataId,$key,$value);
                    }else{
                        $mongoman->unsetSingleValueById("Entity_person_sheet",$dataId,$key);
                    }
                }
            }

            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('manager/entity_people_index', ['id' => $entityPerson->getId()]);
        }

        return $this->render('entity_people/edit.html.twig', [
            'entity_person' => $entityPerson,
            'form' => $form->createView(),
            'entity_person_data' => $mongoman->getDocById("Entity_person_sheet",$entityPerson->getSheetId()),
        ]);
    }

    /**
     * @Route("/{id}", name="manager/entity_people_delete", methods="DELETE")
     */
    public function delete(Request $request, EntityPeople $entityPerson): Response
    {
        if ($this->isCsrfTokenValid('delete'.$entityPerson->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $mongoman = new MongoManager();
            $mongoman->deleteSingleById("Entity_person_sheet",$entityPerson->getSheetId());
            $em->remove($entityPerson);
            $em->flush();
        }

        return $this->redirectToRoute('manager/entity_people_index');
    }
}

app/templates/entity_people/_delete_form.html.twig
<form method="post" action="{{ path('manager/entity_people_delete', {'id': entity_person.id}) }}" onsubmit="return confirm('Êtes vous sûr de vouloir supprimer cette entrée ?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ entity_person.id) }}">
    <button class="btn btn-danger m-1"><i class="fas fa-times"></i> Supprimer</button>
</form>

app/templates/entity_people/_form.html.twig
{% form_theme form 'bootstrap_4_layout.html.twig' %}

{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary m-1"><i class="fas fa-check"></i> {{ button_label|default('Valider') }}</button>
    <a class="btn btn-light m-1" href="{{ path('manager/entity_people_index') }}"><i class="fas fa-undo"></i> Annuler</a>
{{ form_end(form) }}

app/templates/entity_people/edit.html.twig
{% extends 'baselayout.html.twig' %}

{% block title %}Édition de {{ entity_person.name }} {{ entity_person.firstname }}{% endblock %}

{% block content %}
    <h2><i class="fas fa-edit"></i> Édition de {{ entity_person.name }} {{ entity_person.firstname }}</h2>

    {{ include('entity_people/_form.html.twig', {'button_label': 'Valider'}) }}

    {{ include('entity_people/_delete_form.html.twig') }}

    <hr/>
    <h4><i class="fas fa-tags"></i> Affectation de TAGs</h4>
    <i class="text-danger">Tableau temporaire d'exemple non fonctionnel à modifier</i>
    <!--Tableau des tags affect existant récupéré via AJAX-->
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Personne</th>
                <th>Représentation</th>
                <th>TAG</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
                    <tr>
                <td>1</td>
                <td>Test test</td>
                <td>Faust 15/Apr/2019</td>
                <td>guitariste</td>
                <td>
                    <a href="#"><i class="fas fa-times text-danger"></i></a>
                </td>
            </tr>
                </tbody>
    </table>
    <i class="text-danger">Formulaire temporaire d'exemple non fonctionnel à modifier</i>
    <!--Duplication pour chaque tags affect avec un form dynamique AJAX-->
    <form name="tags_affect" method="post">
        <div id="tags_affect">
            <div class="form-group"><label class="required" for="tags_affect_tag">Tag</label>
                <select id="tags_affect_tag" name="tags_affect[tag]" class="form-control">
                    <option value="1">guitariste</option>
                </select>
            </div>
            <div class="form-group"><label class="required" for="tags_affect_performance">Performance</label>
                <select id="tags_affect_performance" name="tags_affect[performance]" class="form-control">
                    <option value="1">Faust 15/Apr/2019</option>
                    <option value="2">Faust 01/Jan/2014</option>
                </select>
            </div>
            <i class="fas fa-exclamation-triangle text-danger"></i><i class="text-danger"> Ne pas inclure cet élément en tant que CHOIX dans le formulaire !!! C'est automatiquement la personne de référence de cette page</i>
            <div class="form-group"><label class="required" for="tags_affect_person">Person</label>
                <select id="tags_affect_person" name="tags_affect[person]" class="form-control">
                    <option value="1">Test test</option>
                    <option value="2">Test1 Test1</option>
                    <option value="3">Test3 Test3</option>
                    <option value="4">FAURIE Thibaud</option>
                </select>
            </div>
            <input type="hidden" id="tags_affect__token" name="tags_affect[_token]" value="IwTHZI-zwMrt8mrsU9zal4_KzuFCeICimEB5Gj59b5Y">
        </div>
        <span class="not-allowed"><a class="btn text-primary mr-2 disabled dotted" href="#"><i class="fas fa-check"></i> Ajouter</a></span>
    </form>
    <br/>
{% endblock %}

app/templates/entity_people/index.html.twig
{% extends 'baselayout.html.twig' %}

{% block title %}Annuaire{% endblock %}

{% block content %}
    <h2><i class="fas fa-users"></i> Liste des personnes</h2>
    <div class="row m-3">
        <a class="btn btn-primary mr-2" href="{{ path('manager/entity_people_new') }}"><i class="fas fa-plus"></i> Ajouter</a>
        <span class="not-allowed"><a class="btn text-warning mr-2 disabled dotted" href=""><i class="fas fa-upload"></i> Importer des données</a></span>
    </div>
        <table class="table table-striped">
            <thead class="bg-secondary text-white">
                <tr>
                    <th><input type="checkbox" id="select-all"></th>
                    <th>Nom</th>
                    <th>Prénom</th>
                    <th>Date de naissance</th>
                    <th>Abonnement à la newsletter</th>
                    <th>Code postal</th>
                    <th>Ville</th>
                    <th>Date d'ajout</th>
                    <th><i class="fas fa-cog"></i></th>
                </tr>
            </thead>
            <tbody>
            {% for entity_person in entity_people %}
                <tr>
                    <td id="{{ entity_person.id }}"><input type="checkbox" name="selected[{{ entity_person.id }}]"></td> <!--VALUE !-->
                    <td>{{ entity_person.name }}</td>
                    <td>{{ entity_person.firstname }}</td>
                    <td>{{ entity_person.birthdate ? entity_person.birthdate|date('Y-m-d') : '' }}</td>
                    <td>{{ entity_person.newsletter ? 'Oui' : 'Non' }}</td>
                    <td>{{ entity_person.postalCode }}</td>
                    <td>{{ entity_person.city }}</td>
                    <td>{{ entity_person.addDate ? entity_person.addDate|date('Y-m-d') : '' }}</td>
                    <td>
                        <a href="{{ path('manager/entity_people_show', {'id': entity_person.id}) }}"><i class="fas fa-eye"></i></a>
                        <a href="{{ path('manager/entity_people_edit', {'id': entity_person.id}) }}"><i class="far fa-edit"></i></a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="10">Aucune entrée</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <nav class="row justify-content-center" aria-label="Page navigation">
            <ul class="pagination">
                <li class="page-item">
                <a class="page-link" href="#!" aria-label="Previous">
                    <span aria-hidden="true"><i class="fas fa-arrow-circle-left"></i></span>
                    <span class="sr-only">Previous</span>
                </a>
                </li>
                <li class="page-item active"><a class="page-link" href="#!">1</a></li>
                <li class="page-item"><a class="page-link" href="#!">2</a></li>
                <li class="page-item"><a class="page-link" href="#!">3</a></li>
                <li class="page-item">
                <a class="page-link" href="#!" aria-label="Next">
                    <span aria-hidden="true"><i class="fas fa-arrow-circle-right"></i></span>
                    <span class="sr-only">Next</span>
                </a>
                </li>
            </ul>
        </nav>
    </div>
{% endblock %}

app/templates/entity_people/new.html.twig
{% extends 'baselayout.html.twig' %}

{% block title %}Ajouter une personne{% endblock %}

{% block content %}
    <h2><i class="fas fa-users"></i> Ajouter une personne</h2>

    {{ include('entity_people/_form.html.twig') }}
    <br/>
</div>
{% endblock %}

app/templates/entity_people/show.html.twig
{% extends 'baselayout.html.twig' %}

{% block title %}Fiche de {{ entity_person.name }} {{ entity_person.firstname }}{% endblock %}

{% block content %}
<div class="col">
    <h2><i class="fas fa-users"></i> Fiche de {{ entity_person.name }} {{ entity_person.firstname }}</h2>

    <table class="table">
        <tbody>
            <tr>
                <th>ID</th>
                <td>{{ entity_person.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ entity_person.name }}</td>
            </tr>
            <tr>
                <th>Prénom</th>
                <td>{{ entity_person.firstname }}</td>
            </tr>
            <tr>
                <th>Date de naissance</th>
                <td>{{ entity_person.birthdate ? entity_person.birthdate|localizeddate('none', 'none', 'fr', null,'d MMMM Y') : '' }}</td>
            </tr>
            <tr>
                <th>Abonnement Newsletter</th>
                <td>{{ entity_person.newsletter ? 'Oui' : 'Non' }}</td>
            </tr>
            <tr>
                <th>Code postal</th>
                <td>{{ entity_person.postalCode }}</td>
            </tr>
            <tr>
                <th>Ville</th>
                <td>{{ entity_person.city }}</td>
            </tr>
            <tr>
                <th>Date d'ajout</th>
                <td>{{ entity_person.addDate ? entity_person.addDate|localizeddate('none', 'none', 'fr', null,'d MMMM Y') : '' }}</td>
            </tr>
            <tr>
                <th>Identifiant de données dynamiques</th>
                <td>{{ entity_person.sheetId }}</td>
            </tr>
        </tbody>
    </table>

    <a class="btn btn-light m-1" href="{{ path('manager/entity_people_index') }}"><i class="fas fa-arrow-left"></i> Retour</a>

    <a class="btn btn-success m-1" href="{{ path('manager/entity_people_edit', {'id': entity_person.id}) }}"><i class="fas fa-edit"></i> Éditer</a>

    {{ include('entity_people/_delete_form.html.twig') }}
</div>
{% endblock %}